name: Workflow_2
on:
  workflow_run:
    workflows: ["Workflow_1"]
    types:
      - completed

jobs:
  use-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myfile

      - name: Show file
        run: cat myfile.txt
