name: Workflow 1
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create file
        run: echo "Hello from workflow 1" > myfile.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myfile
          path: myfile.txt
